// Generated by CoffeeScript 1.6.3

var async = require('async');

  var LolClient = require('./lol-client');

  util = require('util');

  options = {
    region: 'euw',
    username: '',
    password: '',
    version: '3.9.13_07_01_27',
    debug: true
  };

  var client = new LolClient(options);

  client.on('connection', function() {
    console.log('Connected');

    async.waterfall([

      function (callback){

        client.getSummonerByName('NSZombie', function(err, result) {
          callback(err, result);
        });

      }, function (result, callback){

        client.getSummonerStats(result.object.acctId.value, function(err, result) {
          callback(err, result);
        });

      }

    ], function (err, result){

      console.log(err, result);

    });

/*    async.parallel([

      function (callback){
        client.getSummonerStats(36910949, function(err, result) {
          console.log(1);
          callback(err, result);
        });
      }, function (callback){

        client.getSummonerByName('Ichiriki Orihara', function(err, result) {
          console.log(2);
          callback(err, result);
        });

      }

    ], function (err, result){
      console.dir(err, result);
    });*/
    
/*    client.getSummonerStats(summoner.summonerId, function(err, result) {
      console.dir(result);
    });*/
    /*client.getMatchHistory(summoner.acctId, function(err, result) {
      return console.log(util.inspect(result, false, null, true));
    });
    client.getAggregatedStats(summoner.acctId, function(err, result) {
      return console.log(util.inspect(result, false, null, true));
    });
    client.getTeamsForSummoner(summoner.summonerId, function(err, result) {
      return console.log(util.inspect(result, false, null, true));
    });
    client.getTeamById(summoner.teamId, function(err, result) {
      return console.log(util.inspect(result, false, null, true));
    });
    return client.getSummonerData(summoner.acctId, function(err, result) {
      return console.log(util.inspect(result, false, null, true));
    });*/
  
  });

  client.connect();
