// Generated by CoffeeScript 1.6.3
(function() {
  var LolClient, client, options, summoner, util;

  LolClient = require('./lol-client');

  util = require('util');

  options = {
    region: 'euw',
    username: '',
    password: '',
    version: '3.9.13_07_01_27',
    debug: true
  };

  summoner = {
    name: 'HotshotGG',
    acctId: 434582,
    summonerId: 407750,
    teamId: "TEAM-a1ebba15-986f-488a-ae2f-e081b2886ba4"
  };

  client = new LolClient(options);

  client.on('connection', function() {
    console.log('Connected');
    client.getSummonerByName(summoner.name, function(err, result) {
      return console.log(util.inspect(result, false, null, true));
    });
    /*
    client.getSummonerStats(summoner.acctId, function(err, result) {
      return console.log(util.inspect(result, false, null, true));
    });
    client.getMatchHistory(summoner.acctId, function(err, result) {
      return console.log(util.inspect(result, false, null, true));
    });
    client.getAggregatedStats(summoner.acctId, function(err, result) {
      return console.log(util.inspect(result, false, null, true));
    });
    client.getTeamsForSummoner(summoner.summonerId, function(err, result) {
      return console.log(util.inspect(result, false, null, true));
    });
    client.getTeamById(summoner.teamId, function(err, result) {
      return console.log(util.inspect(result, false, null, true));
    });
    return client.getSummonerData(summoner.acctId, function(err, result) {
      return console.log(util.inspect(result, false, null, true));
    });*/
  });

  client.connect();

}).call(this);
